import {
  Merchant,
  PickupSite,
  UserProfile,
  Delivery,
  FinanceMovement,
  Invoice,
  Payout,
  SupportTicket,
} from "./types";

export const MOCK_USERS: UserProfile[] = [
  {
    id: "usr_1",
    name: "Patrick Nguemo",
    email: "p.nguemo@boulangeriemoderne.cm",
    phone: "+237 699 45 12 30",
    role: "owner",
    roleLabel: "Propriétaire",
    avatarInitials: "PN",
    avatarColor: "bg-yolo-lime text-yolo-ink",
    accessibleSiteIds: [],
  },
  {
    id: "usr_2",
    name: "Carine Mbida",
    email: "c.mbida@boulangeriemoderne.cm",
    phone: "+237 677 82 91 04",
    role: "manager",
    roleLabel: "Gestionnaire de site",
    avatarInitials: "CM",
    avatarColor: "bg-emerald-500/20 text-emerald-700 dark:text-emerald-300",
    accessibleSiteIds: ["site_akwa", "site_bonapriso"],
  },
  {
    id: "usr_3",
    name: "Samuel Enyegue",
    email: "s.enyegue@boulangeriemoderne.cm",
    phone: "+237 690 14 38 72",
    role: "preparer",
    roleLabel: "Préparateur de commandes",
    avatarInitials: "SE",
    avatarColor: "bg-amber-500/20 text-amber-700 dark:text-amber-300",
    accessibleSiteIds: ["site_akwa"],
  },
  {
    id: "usr_4",
    name: "Henriette Eyenga",
    email: "h.eyenga@boulangeriemoderne.cm",
    phone: "+237 675 22 67 89",
    role: "accountant",
    roleLabel: "Comptable & Trésorière",
    avatarInitials: "HE",
    avatarColor: "bg-sky-500/20 text-sky-700 dark:text-sky-300",
    accessibleSiteIds: [],
  },
];

export const MOCK_MERCHANT: Merchant = {
  id: "merch_01",
  name: "Boulangerie & Épicerie Fine Moderne",
  legalName: "SARL Les Délices d'Afrique",
  taxId: "M051800049281X",
  category: "restaurant",
  categoryLabel: "Alimentation & Traiteur",
  phone: "+237 699 45 12 30",
  email: "contact@boulangeriemoderne.cm",
  address: "Boulevard de la Liberté, Akwa",
  city: "Douala",
  status: "active",
  currency: "FCFA",
  contractRateDiscount: 10,
  mobileMoneyAccount: {
    provider: "MTN MoMo",
    number: "+237 677 00 11 22",
    verified: true,
  },
  bankAccount: {
    bankName: "Afriland First Bank (Siège Douala)",
    ibanOrRib: "CM21 10005 00012 049281001 45",
    verified: true,
  },
};

export const MOCK_PICKUP_SITES: PickupSite[] = [
  {
    id: "site_akwa",
    merchantId: "merch_01",
    name: "Boutique Centrale Akwa",
    address: "128 Boulevard de la Liberté, face Direction Orange",
    city: "Douala",
    neighborhood: "Akwa",
    lat: 4.0511,
    lng: 9.7085,
    contactName: "Samuel Enyegue",
    contactPhone: "+237 690 14 38 72",
    instructions: "Entrée côté comptoir retrait coursier, sonner à la cloche Yolo.",
    openingHours: "Lun - Sam : 07h00 - 21h00",
    active: true,
    isDefault: true,
  },
  {
    id: "site_bonapriso",
    merchantId: "merch_01",
    name: "Atelier Traiteur Bonapriso",
    address: "Rue Tokoto, face Clinique de la Gare",
    city: "Douala",
    neighborhood: "Bonapriso",
    lat: 4.0289,
    lng: 9.6974,
    contactName: "Carine Mbida",
    contactPhone: "+237 677 82 91 04",
    instructions: "Dépose-minute disponible. Retrait sur présentation du QR code.",
    openingHours: "Lun - Dim : 08h00 - 22h00",
    active: true,
    isDefault: false,
  },
  {
    id: "site_bonamoussadi",
    merchantId: "merch_01",
    name: "Point Retrait Bonamoussadi",
    address: "Rond-point Denver, Immeuble Horizon 1er étage",
    city: "Douala",
    neighborhood: "Bonamoussadi",
    lat: 4.0845,
    lng: 9.7341,
    contactName: "Pauline Tchinda",
    contactPhone: "+237 693 40 18 55",
    instructions: "Accès par l'escalier extérieur.",
    openingHours: "Mar - Dim : 09h00 - 20h00",
    active: true,
    isDefault: false,
  },
  {
    id: "site_bastos",
    merchantId: "merch_01",
    name: "Comptoir Bastos (Yaoundé)",
    address: "Rue Joseph Mballa Eloumden, Bastos",
    city: "Yaoundé",
    neighborhood: "Bastos",
    lat: 3.8821,
    lng: 11.5167,
    contactName: "Jean-Marc Fouda",
    contactPhone: "+237 655 12 78 90",
    instructions: "Près de l'Ambassade de Suisse.",
    openingHours: "Lun - Sam : 08h30 - 19h30",
    active: true,
    isDefault: false,
  },
];

export const MOCK_DELIVERIES: Delivery[] = [
  {
    id: "del_01",
    reference: "YLO-2026-09-8491",
    trackingToken: "trk_8491_x9f2q",
    merchantId: "merch_01",
    pickupSiteId: "site_akwa",
    pickupSiteName: "Boutique Centrale Akwa",
    pickupAddress: "128 Bd de la Liberté, Akwa",
    pickupNeighborhood: "Akwa",
    recipientName: "Dr. André Mvondo",
    recipientPhone: "+237 677 12 34 56",
    recipientAddress: "Polyclinique Sainte-Anne, Rue Njo-Njo",
    recipientCity: "Douala",
    recipientNeighborhood: "Bonapriso",
    recipientInstructions: "Demander au secrétariat du 2ème étage Dr. Mvondo.",
    items: [
      { id: "it_1", name: "Plateau Traiteur Cocktail Salé (40 pièces)", quantity: 1, category: "food", weightKg: 2.5 },
      { id: "it_2", name: "Gâteau Pâtissier Forêt Noire 8 pers.", quantity: 1, category: "fragile", weightKg: 1.8 },
    ],
    packageCount: 2,
    estimatedWeightKg: 4.3,
    declaredValue: 35000,
    isFragile: true,
    status: "at_pickup",
    createdAt: "2026-09-22T11:45:00Z",
    scheduledPickupTime: "2026-09-22T12:15:00Z",
    pickupVerificationCode: "482-901",
    recipientDeliveryPin: "7193",
    assignedCourier: {
      id: "courier_01",
      name: "Martin Kamga",
      phone: "+237 694 22 18 90",
      vehicleType: "moto",
      plateNumber: "LT 482 EK",
      rating: 4.9,
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80",
      verified: true,
      estimatedArrivalMinutes: 0,
    },
    paymentMode: "cash_on_delivery",
    goodsAmount: 35000,
    transportFee: 1750,
    transportPayer: "merchant",
    totalToCollect: 35000,
    reconciliationStatus: "pending",
    timeline: [
      { id: "tl_1", timestamp: "11:45", status: "draft", title: "Demande créée", description: "Saisie manuelle par Samuel Enyegue", actor: "merchant" },
      { id: "tl_2", timestamp: "11:48", status: "searching_courier", title: "Colis déclarés prêts", description: "Emballage terminé, recherche livreur PostGIS lancée", actor: "merchant" },
      { id: "tl_3", timestamp: "11:51", status: "courier_assigned", title: "Livreur attribué", description: "Martin Kamga (Moto LT 482 EK) a accepté la course", actor: "courier", actorName: "Martin Kamga" },
      { id: "tl_4", timestamp: "12:05", status: "at_pickup", title: "Livreur arrivé au retrait", description: "En attente du contrôle et du scan de remise", actor: "courier" },
    ],
  },
  {
    id: "del_02",
    reference: "YLO-2026-09-8488",
    trackingToken: "trk_8488_p4k8m",
    merchantId: "merch_01",
    pickupSiteId: "site_akwa",
    pickupSiteName: "Boutique Centrale Akwa",
    pickupAddress: "128 Bd de la Liberté, Akwa",
    pickupNeighborhood: "Akwa",
    recipientName: "Béatrice Ebelle",
    recipientPhone: "+237 699 55 43 21",
    recipientAddress: "Villa 14, Cité des Palmiers",
    recipientCity: "Douala",
    recipientNeighborhood: "Cité des Palmiers",
    recipientInstructions: "Portail noir avec bougainvilliers.",
    items: [
      { id: "it_3", name: "Coffret Brunch Prestige (Viennoiseries + Jus)", quantity: 2, category: "food", weightKg: 3.0 },
    ],
    packageCount: 1,
    estimatedWeightKg: 3.0,
    declaredValue: 24000,
    isFragile: false,
    status: "in_transit",
    createdAt: "2026-09-22T10:30:00Z",
    actualPickupTime: "2026-09-22T11:15:00Z",
    pickupVerificationCode: "109-842",
    recipientDeliveryPin: "3845",
    assignedCourier: {
      id: "courier_02",
      name: "Fabrice Onana",
      phone: "+237 671 90 44 12",
      vehicleType: "moto",
      plateNumber: "LT 912 AB",
      rating: 4.8,
      verified: true,
      estimatedArrivalMinutes: 12,
    },
    paymentMode: "cash_on_delivery",
    goodsAmount: 24000,
    transportFee: 2200,
    transportPayer: "recipient",
    totalToCollect: 26200,
    reconciliationStatus: "pending",
    timeline: [
      { id: "tl_5", timestamp: "10:30", status: "draft", title: "Commande Yolo Web", description: "Générée automatiquement depuis boutique en ligne", actor: "system" },
      { id: "tl_6", timestamp: "10:45", status: "courier_assigned", title: "Livreur attribué", description: "Fabrice Onana en route vers le retrait", actor: "courier" },
      { id: "tl_7", timestamp: "11:15", status: "in_transit", title: "Remise validée par QR code", description: "Colis remis à Fabrice Onana, transport en cours", actor: "merchant" },
    ],
  },
  {
    id: "del_03",
    reference: "YLO-2026-09-8480",
    trackingToken: "trk_8480_z1w9e",
    merchantId: "merch_01",
    pickupSiteId: "site_bonapriso",
    pickupSiteName: "Atelier Traiteur Bonapriso",
    pickupAddress: "Rue Tokoto, Bonapriso",
    pickupNeighborhood: "Bonapriso",
    recipientName: "Société Gecam Assurances (M. Manga)",
    recipientPhone: "+237 694 00 99 88",
    recipientAddress: "Immeuble Allianz, 4ème étage, Rue Koumassi",
    recipientCity: "Douala",
    recipientNeighborhood: "Bali",
    items: [
      { id: "it_4", name: "Buffet Déjeuner 15 Personnes (3 cartons isothermes)", quantity: 3, category: "food", weightKg: 12.0 },
    ],
    packageCount: 3,
    estimatedWeightKg: 12.0,
    declaredValue: 95000,
    isFragile: true,
    status: "delivered",
    createdAt: "2026-09-22T08:15:00Z",
    actualPickupTime: "2026-09-22T09:10:00Z",
    deliveredTime: "2026-09-22T09:42:00Z",
    pickupVerificationCode: "772-194",
    recipientDeliveryPin: "5502",
    assignedCourier: {
      id: "courier_03",
      name: "Arnaud Tchuente",
      phone: "+237 670 33 11 00",
      vehicleType: "van",
      plateNumber: "LT 103 CG",
      rating: 4.95,
      verified: true,
    },
    paymentMode: "cash_on_delivery",
    goodsAmount: 95000,
    transportFee: 3500,
    transportPayer: "merchant",
    totalToCollect: 95000,
    cashCollected: 95000,
    collectionMethod: "MTN MoMo",
    reconciliationStatus: "reconciled_j0",
    timeline: [
      { id: "tl_8", timestamp: "08:15", status: "draft", title: "Commande créée", description: "Buffet corporate", actor: "merchant" },
      { id: "tl_9", timestamp: "09:10", status: "in_transit", title: "Prise en charge Van", description: "Cartons chargés dans le van réfrigéré", actor: "courier" },
      { id: "tl_10", timestamp: "09:42", status: "delivered", title: "Livrée avec preuve PIN", description: "Encaissé 95 000 FCFA via MTN MoMo, code PIN vérifié", actor: "courier" },
    ],
  },
  {
    id: "del_04",
    reference: "YLO-2026-09-8475",
    trackingToken: "trk_8475_r8t3v",
    merchantId: "merch_01",
    pickupSiteId: "site_bonamoussadi",
    pickupSiteName: "Point Retrait Bonamoussadi",
    pickupAddress: "Rond-point Denver, Bonamoussadi",
    pickupNeighborhood: "Bonamoussadi",
    recipientName: "Sandrine Kotto",
    recipientPhone: "+237 691 77 66 55",
    recipientAddress: "Entrée Kotto Immeuble Rose",
    recipientCity: "Douala",
    recipientNeighborhood: "Kotto",
    items: [
      { id: "it_5", name: "Coffret Pâtisseries Macarons & Éclairs", quantity: 1, category: "food", weightKg: 1.2 },
    ],
    packageCount: 1,
    estimatedWeightKg: 1.2,
    declaredValue: 16500,
    isFragile: true,
    status: "incident",
    createdAt: "2026-09-22T09:00:00Z",
    actualPickupTime: "2026-09-22T09:50:00Z",
    pickupVerificationCode: "331-509",
    recipientDeliveryPin: "9012",
    assignedCourier: {
      id: "courier_04",
      name: "David Nganou",
      phone: "+237 678 19 28 37",
      vehicleType: "moto",
      plateNumber: "LT 670 BB",
      rating: 4.7,
      verified: true,
    },
    paymentMode: "cash_on_delivery",
    goodsAmount: 16500,
    transportFee: 1500,
    transportPayer: "merchant",
    totalToCollect: 16500,
    incidentReason: "Destinataire injoignable après 3 appels et 20 min d'attente sur place.",
    incidentNotes: "Le livreur a contacté le support. Demande d'autorisation de retour vers le point de retrait Bonamoussadi.",
    isReturnInitiated: true,
    reconciliationStatus: "pending",
    timeline: [
      { id: "tl_11", timestamp: "09:00", status: "draft", title: "Commande créée", description: "Livraison Kotto", actor: "merchant" },
      { id: "tl_12", timestamp: "09:50", status: "in_transit", title: "Retrait effectué", description: "En cours de livraison", actor: "courier" },
      { id: "tl_13", timestamp: "10:25", status: "at_destination", title: "Arrivé chez le client", description: "Sonnette muette, appels non répondus", actor: "courier" },
      { id: "tl_14", timestamp: "10:48", status: "incident", title: "Incident ouvert", description: "Client injoignable, retour vers Bonamoussadi préconisé", actor: "support" },
    ],
  },
  {
    id: "del_05",
    reference: "YLO-2026-09-8470",
    trackingToken: "trk_8470_m2a1c",
    merchantId: "merch_01",
    pickupSiteId: "site_akwa",
    pickupSiteName: "Boutique Centrale Akwa",
    pickupAddress: "128 Bd de la Liberté, Akwa",
    pickupNeighborhood: "Akwa",
    recipientName: "Cabinet Juridique Maître Ebongue",
    recipientPhone: "+237 677 40 50 60",
    recipientAddress: "Rue Joss, face Tribunal Administratif",
    recipientCity: "Douala",
    recipientNeighborhood: "Bonanjo",
    items: [
      { id: "it_6", name: "Coffret Cadeau Partenaire Entreprise", quantity: 2, category: "general_goods", weightKg: 4.0 },
    ],
    packageCount: 2,
    estimatedWeightKg: 4.0,
    declaredValue: 48000,
    isFragile: false,
    status: "delivered",
    createdAt: "2026-09-22T08:00:00Z",
    actualPickupTime: "2026-09-22T08:35:00Z",
    deliveredTime: "2026-09-22T09:05:00Z",
    pickupVerificationCode: "820-112",
    recipientDeliveryPin: "4419",
    assignedCourier: {
      id: "courier_01",
      name: "Martin Kamga",
      phone: "+237 694 22 18 90",
      vehicleType: "moto",
      plateNumber: "LT 482 EK",
      rating: 4.9,
      verified: true,
    },
    paymentMode: "prepaid",
    goodsAmount: 48000,
    transportFee: 1500,
    transportPayer: "merchant",
    totalToCollect: 0,
    reconciliationStatus: "reconciled_j0",
    timeline: [
      { id: "tl_15", timestamp: "08:00", status: "draft", title: "Commande créée", description: "Payée par virement direct", actor: "merchant" },
      { id: "tl_16", timestamp: "08:35", status: "in_transit", title: "Prise en charge", description: "Retrait effectué", actor: "courier" },
      { id: "tl_17", timestamp: "09:05", status: "delivered", title: "Livrée", description: "Réceptionné par l'accueil du cabinet", actor: "courier" },
    ],
  },
  {
    id: "del_06",
    reference: "YLO-2026-09-8465",
    trackingToken: "trk_8465_u7y4s",
    merchantId: "merch_01",
    pickupSiteId: "site_bastos",
    pickupSiteName: "Comptoir Bastos (Yaoundé)",
    pickupAddress: "Rue Joseph Mballa Eloumden, Bastos",
    pickupNeighborhood: "Bastos",
    recipientName: "Honorable Njié",
    recipientPhone: "+237 699 11 22 33",
    recipientAddress: "Quartier Golf, Résidence 4B",
    recipientCity: "Yaoundé",
    recipientNeighborhood: "Golf",
    items: [
      { id: "it_7", name: "Panier Épicerie Fine & Champagne Gourmand", quantity: 1, category: "fragile", weightKg: 5.5 },
    ],
    packageCount: 1,
    estimatedWeightKg: 5.5,
    declaredValue: 80000,
    isFragile: true,
    status: "searching_courier",
    createdAt: "2026-09-22T12:30:00Z",
    pickupVerificationCode: "914-720",
    recipientDeliveryPin: "1182",
    paymentMode: "cash_on_delivery",
    goodsAmount: 80000,
    transportFee: 2500,
    transportPayer: "merchant",
    totalToCollect: 80000,
    reconciliationStatus: "pending",
    timeline: [
      { id: "tl_18", timestamp: "12:30", status: "draft", title: "Commande créée", description: "Saisie Bastos", actor: "merchant" },
      { id: "tl_19", timestamp: "12:35", status: "searching_courier", title: "Recherche de livreur", description: "En attente d'acceptation par les coursiers Bastos/Golf", actor: "system" },
    ],
  },
];

export const MOCK_FINANCE_MOVEMENTS: FinanceMovement[] = [
  {
    id: "mov_01",
    date: "Aujourd'hui, 09:42",
    reference: "MOV-2026-09-8480",
    deliveryReference: "YLO-2026-09-8480",
    type: "cod_collection",
    typeLabel: "Collecte Marchandise (COD)",
    amount: 95000,
    isCredit: true,
    channel: "MTN MoMo",
    status: "effectué",
    description: "Encaissement auprès de Société Gecam Assurances via MoMo",
  },
  {
    id: "mov_02",
    date: "Aujourd'hui, 09:42",
    reference: "MOV-TF-8480",
    deliveryReference: "YLO-2026-09-8480",
    type: "transport_fee_debit",
    typeLabel: "Frais de transport course",
    amount: 3500,
    isCredit: false,
    channel: "Compte Yolo",
    status: "effectué",
    description: "Course Bonapriso -> Bali (Camionnette)",
  },
  {
    id: "mov_03",
    date: "Aujourd'hui, 09:05",
    reference: "MOV-TF-8470",
    deliveryReference: "YLO-2026-09-8470",
    type: "transport_fee_debit",
    typeLabel: "Frais de transport course",
    amount: 1500,
    isCredit: false,
    channel: "Compte Yolo",
    status: "effectué",
    description: "Course Akwa -> Bonanjo (Moto)",
  },
  {
    id: "mov_04",
    date: "Hier, 18:00",
    reference: "REV-2026-09-021",
    type: "payout_credit",
    typeLabel: "Reversement Net Commerçant",
    amount: 485000,
    isCredit: false,
    channel: "MTN MoMo",
    status: "effectué",
    description: "Reversement quotidien automatisé J+0 vers compte MTN MoMo",
  },
  {
    id: "mov_05",
    date: "Hier, 16:30",
    reference: "MOV-2026-09-8450",
    deliveryReference: "YLO-2026-09-8450",
    type: "cod_collection",
    typeLabel: "Collecte Marchandise (COD)",
    amount: 142000,
    isCredit: true,
    channel: "Orange Money",
    status: "effectué",
    description: "Encaissement client Bonamoussadi via Orange Money",
  },
  {
    id: "mov_06",
    date: "Hier, 14:15",
    reference: "MOV-2026-09-8442",
    deliveryReference: "YLO-2026-09-8442",
    type: "cod_collection",
    typeLabel: "Collecte Marchandise (COD)",
    amount: 68000,
    isCredit: true,
    channel: "Espèces",
    status: "effectué",
    description: "Rapprochement espèces remis par livreur au hub central Yolo",
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: "inv_01",
    number: "FAC-YLO-2026-08",
    period: "Août 2026",
    totalDeliveries: 1248,
    totalTransportFees: 1740000,
    taxAmount: 334950,
    netPayable: 2074950,
    status: "payée",
    dueDate: "2026-09-05",
  },
  {
    id: "inv_02",
    number: "FAC-YLO-2026-07",
    period: "Juillet 2026",
    totalDeliveries: 1112,
    totalTransportFees: 1545000,
    taxAmount: 297412,
    netPayable: 1842412,
    status: "payée",
    dueDate: "2026-08-05",
  },
];

export const MOCK_PAYOUTS: Payout[] = [
  {
    id: "pay_01",
    reference: "REV-2026-09-021",
    period: "21 Septembre 2026",
    grossCodAmount: 512000,
    deductedFees: 27000,
    netPayoutAmount: 485000,
    method: "MTN MoMo",
    accountNumber: "+237 677 00 11 22",
    status: "virement_effectué",
    date: "2026-09-21T18:00:00Z",
    traceId: "MTN-PAY-20260921-99841",
  },
  {
    id: "pay_02",
    reference: "REV-2026-09-020",
    period: "20 Septembre 2026",
    grossCodAmount: 420000,
    deductedFees: 22500,
    netPayoutAmount: 397500,
    method: "MTN MoMo",
    accountNumber: "+237 677 00 11 22",
    status: "virement_effectué",
    date: "2026-09-20T18:00:00Z",
    traceId: "MTN-PAY-20260920-88412",
  },
  {
    id: "pay_03",
    reference: "REV-2026-09-022",
    period: "Aujourd'hui (En cours)",
    grossCodAmount: 178000,
    deductedFees: 8250,
    netPayoutAmount: 169750,
    method: "MTN MoMo",
    accountNumber: "+237 677 00 11 22",
    status: "programmé",
    date: "2026-09-22T18:00:00Z",
    traceId: "PENDING-RECONCILIATION-J0",
  },
];

export const MOCK_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: "tck_01",
    subject: "Client injoignable sur livraison Kotto #YLO-2026-09-8475",
    deliveryReference: "YLO-2026-09-8475",
    category: "recipient_absent",
    status: "in_progress",
    priority: "urgent",
    createdAt: "Aujourd'hui, 10:48",
    updatedAt: "Il y a 15 min",
    messagesCount: 4,
  },
  {
    id: "tck_02",
    subject: "Demande d'extension de plage horaire de retrait Bonapriso",
    category: "general",
    status: "resolved",
    priority: "medium",
    createdAt: "18 Sept 2026",
    updatedAt: "19 Sept 2026",
    messagesCount: 2,
  },
];

// Recharts Analytics Data (inspired by CFC Monthly & Distribution charts)
export const MONTHLY_DELIVERY_DATA = [
  { month: "Avr", deliveries: 840, codAmount: 8.2, fees: 1.15, successRate: 97.4 },
  { month: "Mai", deliveries: 1020, codAmount: 10.5, fees: 1.38, successRate: 98.0 },
  { month: "Juin", deliveries: 1150, codAmount: 11.8, fees: 1.52, successRate: 97.8 },
  { month: "Juil", deliveries: 1220, codAmount: 12.6, fees: 1.65, successRate: 98.4 },
  { month: "Août", deliveries: 1390, codAmount: 13.9, fees: 1.78, successRate: 98.1 },
  { month: "Sept", deliveries: 1482, codAmount: 14.85, fees: 1.85, successRate: 98.6 },
];

export const PICKUP_SITE_DISTRIBUTION = [
  { name: "Centrale Akwa", value: 44, color: "#121317" },
  { name: "Atelier Bonapriso", value: 28, color: "#CAF76F" },
  { name: "Denver Bonamoussadi", value: 16, color: "#BC5F28" },
  { name: "Bastos Yaoundé", value: 12, color: "#73766F" },
];

export const CATEGORY_DISTRIBUTION = [
  { name: "Restauration & Repas", value: 52, color: "#CAF76F" },
  { name: "Épicerie & Traiteur", value: 26, color: "#121317" },
  { name: "Pâtisserie & Fragile", value: 14, color: "#BC5F28" },
  { name: "Colis Express", value: 8, color: "#356343" },
];

export const SITE_PERFORMANCE_METRICS = [
  {
    site: "Boutique Centrale Akwa",
    deliveries: "652 courses",
    avgPickupTime: "3m 45s",
    successRate: "99.1%",
    totalCod: "6 840 000 FCFA",
    activeCouriers: 8,
  },
  {
    site: "Atelier Traiteur Bonapriso",
    deliveries: "418 courses",
    avgPickupTime: "4m 12s",
    successRate: "98.5%",
    totalCod: "4 320 000 FCFA",
    activeCouriers: 5,
  },
  {
    site: "Denver Bonamoussadi",
    deliveries: "234 courses",
    avgPickupTime: "4m 50s",
    successRate: "97.2%",
    totalCod: "2 150 000 FCFA",
    activeCouriers: 3,
  },
  {
    site: "Comptoir Bastos Yaoundé",
    deliveries: "178 courses",
    avgPickupTime: "4m 30s",
    successRate: "98.8%",
    totalCod: "1 540 000 FCFA",
    activeCouriers: 4,
  },
];
